name: Build Test Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: default

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: "${{ vars.DOCKERHUB_USERNAME }}/interview1:latest"

    # These steps im leaving in a comment as I don't have a k8s cluster to actually install in so its just an example
    # - name: Setup kubeconfig
    #   uses: azure/k8s-set-context@v4
    #   with:
    #     method: kubeconfig
    #     kubeconfig: ${{ secrets.KUBECONFIG }}
    #     context: default

    # - name: Install Helm
    #   uses: azure/setup-helm@v1

    # - name: Deploy to Kubernetes using Helm
    #   env:
    #     KUBECONFIG: ${{ github.workspace }}/kubeconfig
    #   run: |
    #    cd chart helm upgrade --install my-app . --namespace default

    # add email if success
    - uses: cinotify/github-action@main
      with:
        to: ${{ vars.EMAIL }}
        subject: 'Success on building and deploying main'
        body: '<em>This is a notification from GitHub actions: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}.</em>'
        type: 'text/html'

    # Add email if fail that something failed
    - uses: cinotify/github-action@main
      if: ${{ failure() }}
      with:
        to: ${{ vars.EMAIL }}
        subject: 'Failure on building and deploying main'
        body: '<em>This is a notification from GitHub actions: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID.</em>'
        type: 'text/html'



